### ISSUE TITLE
Fungible Token KIP proposal

### ISSUE THREAD

**Issue by slpopejoy** [kadena-io/KIPs#3]
Pre-discussion and design for KIP PR. 

FungibleAsset specifies an ERC-20-style API. https://eips.ethereum.org/EIPS/eip-20

Design Questions:
- Understand related/extending interfaces from ERC and elsewhere, e.g. whitelisting, burn/create.
    - ERC-1404 https://medium.com/erc1404/erc-1404-simple-restricted-token-standard-f71290a48faa
    - ERC-223 (burn/create) https://github.com/ethereum/EIPs/issues/223
- Address Pact issue regarding extending interfaces https://github.com/kadena-io/pact/issues/408
-  Look at Corda's FungibleAsset interface. Very OO-ey and hard to track down all the supertypes though
    - https://github.com/corda/corda/blob/dd60ae27f2dadd12d121d3ecbb951bdaf2725272/core/src/main/kotlin/net/corda/core/contracts/FungibleAsset.kt
    - https://docs.corda.net/contract-catalogue.html#cash
    - https://github.com/corda/corda/search?q=fungibleasset&unscoped_q=fungibleasset

**Comment by joelburget** [comment]
Is there any constraint on the strings `transfer`, `transfer-to`, and `create-account` return? I assume they're expected to be something like "success"?

When we say "create account with guard", does that mean that it's expected that the row representing the user is expected to have a `guard` field?

@bts I think the stronger property system would be useful for expressing the (currently informal) failure properties ("Fails if account does not exist").

Spelling nits:
* "reciever" should be "receiver"
* "transferrable" should be "transferable"

**Comment by bts** [comment]
> @bts I think the stronger property system would be useful for expressing the (currently informal) failure properties ("Fails if account does not exist").

When I was reading the proposal I had the same thought! One way we could do this here would be a combination of:

(1) implement kadena-io/pact#124
(2) add one more function to the interface that we can reference in properties:

```lisp
(defun account-exists:bool (account:string))
```

**Comment by bts** [comment]
Hm GitHub claims I unassigned @lilamila but alas, I did not. Re-assigning.

**Comment by slpopejoy** [comment]
> Is there any constraint on the strings transfer, transfer-to, and create-account return? I assume they're expected to be something like "success"?

It would probably be good to lock these down but OTOH they don't represent meaningful values in the interface. But we could certainly limit their length. Or just make them `bool` ...

> When we say "create account with guard", does that mean that it's expected that the row representing the user is expected to have a guard field?

This is the essence of the difference between `transferTo` and `transfer`: the latter operates like Ethereum where if that address doesn't exist (and is valid) then it is simply created. When it does exist, the requirement is currently that the guard must exactly match the existing guard, which is admittedly awkward, but in fact is no different from the single-signature semantics of say Ethereum where the ID and the public key have been conflated into a single value, which is obviously inadequate for say, multi-sig. 

One thing we haven't addressed in this interface is key rotation but I would imagine that being part of some `RotatableAccount` API that would equally apply to non-fungible ledgers, etc.

**Comment by slpopejoy** [comment]
Along with `accounts-exist`, I was wondering if we could simulate `column-delta` properties with another operation `get-ledger:[object{keyed-ledger}]` (where `keyed-ledger` is simply `{acct:string, balance:decimal}`) that returns the entire ledger? In general, what is required for model-checking to do column-delta stuff on an interface?

**Comment by slpopejoy** [comment]
Note this was implemented in #7 and released with Chainweb in October 2019.
