### ISSUE TITLE
Coin Contract KIP Proposal

### ISSUE THREAD

**Issue by mercadoa** [kadena-io/KIPs#4]

**Comment by emilypi** [comment]
Further updates: We've removed `create-coin` and `delete-coin` as standalone functions, and created a new function, `cross-chain-transfer`, which encapsulates this behavior as a two-step cross-chain `defpact`. This behavior is equivalent and is current as of TestNet V2

**Comment by slpopejoy** [comment]
This never had a discussion period, and was released as part of Chainweb in 2019, so we'll skip making this a retroactive KIP.
