### ISSUE TITLE
Decryption Primitives

### ISSUE THREAD

**Issue by slpopejoy** [kadena-io/KIPs#5]
Proposal is to add two new operations as built-ins:

- `validate-keypair` to match up a public key with a private key for some scheme(s)
- `decrypt` to decrypt ciphertext to plaintext using a keypair for some scheme(s)

Considerations:

* **Use [noise-protocol--endorsed configurations](https://noiseprotocol.org/noise.html#dh-functions-cipher-functions-and-hash-functions) only.** Initial proposal would be DH 25519 with AESGCM following all configuration [recos](https://noiseprotocol.org/noise.html#cipher-functions) such as nonce size, etc.

* **Supporting more than one configuration**, ie RSA, ED 448. Preference is to start with just configuration above and introduce overloaded versions later as needed.

**Comment by slpopejoy** [comment]
Curve25519 is the superior algorithm in multiple ways: as strong as 3000bit RSA (http://ed25519.cr.yp.to/), has smaller keys and is much faster. However, RSA is a simpler scheme in that it uses a single keypair, whereas Curve25519 is a DH process, in which both sides generate keypairs and exchange public keys. (https://cr.yp.to/ecdh.html)


RSA:
1. Reader generates (pkR,skR) and shares pkR with writer.
2. Writer encrypts data D with pkR to get ciphertext C, and shares C with reader.
4. Reader decrypts C with skR.

Curve25519:
1. Reader generates (pkR,skR) and shares pkR with writer.
2. Writer generates (pkW,skW). Writer computes secret from (skW,pkR).
3. Writer encrypts data D with secret to get C, and shares (C,pkW) with reader.
4. Reader computes secret from (skR,pkW) and decrypts C with secret.

**Comment by arjunbaokar** [comment]
Some extra considerations and specificity we want to explore (which you may have already been thinking of):

1. Assuming `validate-keypair` returns a boolean value indicating if the keypair matches, we should make sure that we don't hit exceptions for arbitrary input (ie. crafted maliciously) passed to the function. Basically, in the "The keypair is invalid if false or error" vs "The keypair is invalid iff false", I'd aim for the latter, because it provides a cleaner interface for the user, but involves more checks in the `validate-keypair` code.
2. Which underlying Haskell libs do we want to use?
3. Let's specify the data formats are we following for keys/ciphertexts/etc. I assume we'll be following the standard set by the underlying libs, probably something similar to [TweetNaCl](https://tweetnacl.cr.yp.to/). We should specify these for other 

I'd love to see the exact interfaces you're imagining for this, or a draft implementation.

The interfaces are pretty straightforward for Curve25519-only support, but need to dictate formats when working with other configurations:
`(defun validate-keypair (config:string publicKey:string privateKey:string))
(defun decrypt (config:string ciphertext:string privateKey:string))`
with config being an enum specifying what we support. The key formats would change accordingly (PEM for RSA, etc).

An additional piece of functionality we'd find helpful is to parse keys for their components (eg. parse `n` and `e` from an RSA public key), but that should definitely not be part of these two primitives.

**Comment by slpopejoy** [comment]
> "The keypair is invalid if false or error" vs "The keypair is invalid iff false", I'd aim for the latter, because it provides a cleaner interface for the user, but involves more checks in the `validate-keypair` code.

`validate-keypair` would fail on any error, formatting or mismatch, following the Pact credo of avoiding control-flow on invalid or incorrect data. The format will absolutely be validated, and things like really long strings will be handled by the gas model (and won't be an issue for the underlying Haskell code in any case).

> Which underlying Haskell libs do we want to use?

`cryptonite` is the standard approach, you can see its c implementations here: https://github.com/haskell-crypto/cryptonite/tree/master/cbits

> Let's specify the data formats are we following for keys/ciphertexts/etc

Pact so far has used:

- base16 strings for ed25519
- unpadded base64url for blake2b256 hashes

and exports both of these in the current js library. I would propose we stick with these, tweetnacl just uses Uint8Array via Buffer etc so it's however we want to represent them. Base16 is a relatively uncontroversial choice.

**Comment by slpopejoy** [comment]
> The interfaces are pretty straightforward for Curve25519-only support, but we'd need to dictate formats when working with other configurations

If we're agreed to start with Curve25519, then we can later overload with the additional `string` argument.

**Comment by slpopejoy** [comment]
Here are proposed signatures. Note that `decrypt` takes a key _pair_, not just a secret key, due to the DH process.

```
pact> validate-keypair
native `validate-keypair`
  
  Test that the Curve25519 keypair of (PUBLIC,SECRET) match, and fail if not.
  Key values are base-16 strings of length 32 each.
  
  Type:
  public:string secret:string -> bool
  
  
pact> decrypt
native `decrypt`
  
  Given Curve25519 PUBLIC-KEY and SECRET-KEY, attempt to decrypt CIPHERTEXT to
  plaintext string, failing on error. PUBLIC-KEY and SECRET-KEY are base-16
  strings of length 32 each.
  
  Type:
  ciphertext:string public-key:string secret-key:string -> string
  
```

**Comment by arjunbaokar** [comment]
>Here are proposed signatures. Note that decrypt takes a key pair, not just a secret key, due to the DH process.
Oops yes, my mistake. I was looking at the interfaces we were using for RSA and forgot to convert.

>Base16 is a relatively uncontroversial choice.
SGTM, base16 is what I thought most libs used.

>Initial proposal would be DH 25519 with AESGCM
Would it be terribly difficult to support XSalsa20? I took a brief look at what the most-used NodeJS and Go libraries for Curve25519 encryption do, and they tend to default to NaCl Box's Curve25519/XSalsa20/Poly1305 implementation of encryption. I can also look further to find other options, but I'd generally prefer to use the most popular libs for crypto operations. We could try to chain other libs' functions together to plug in AES-GCM it seems, but it seems easier to line up with what nacl box does to start with. Thoughts?

**Comment by Kenadia** [comment]
> Given Curve25519 PUBLIC-KEY and SECRET-KEY, attempt to decrypt CIPHERTEXT to
  plaintext string, failing on error. PUBLIC-KEY and SECRET-KEY are base-16
  strings of length 32 each.

The ciphertext also needs its encoding to be specified I think. I still don't have a very good sense of storage costs on Chainweb but I feel like the inefficiency of Base16 could become a concern for our use case, especially if it's used for ciphertexts.

By the way is binary data in Pact out of the question @slpopejoy ?

**Comment by Kenadia** [comment]
> Given Curve25519 PUBLIC-KEY and SECRET-KEY, attempt to decrypt CIPHERTEXT to
  plaintext string, failing on error. PUBLIC-KEY and SECRET-KEY are base-16
  strings of length 32 each.

The ciphertext also needs its encoding to be specified I think. I still don't have a very good sense of exact storage costs on Chainweb but I feel like the inefficiency of Base16 could become a concern for our use case, especially if it's used for ciphertexts.

By the way is binary data in Pact out of the question @slpopejoy ?

**Comment by arjunbaokar** [comment]
I would think ciphertexts would follow the same encoding as hash results (base64)

**Comment by slpopejoy** [comment]
> The ciphertext also needs its encoding to be specified I think

Agree with @arjunbaokar that unpadded base64url for this a la Pact's hashes. I'll update the proposal.

> is binary data in Pact out of the question

`string` is preferred because it naturally converts to JSON, thus pact hashes are `string` etc.

**Comment by slpopejoy** [comment]
> Would it be terribly difficult to support XSalsa20? I took a brief look at what the most-used NodeJS and Go libraries for Curve25519 encryption do, and they tend to default to NaCl Box's Curve25519/XSalsa20/Poly1305

We can certainly consider this, I think the choice in Noise has more to do with using the same stack on both sides whereas this obviously needs to interop with a relatively unrelated client side. I'll look into XSalsa20.

**Comment by slpopejoy** [comment]
> > Note that decrypt takes a key pair, not just a secret key, due to the DH process

> I was looking at the interfaces we were using for RSA 

> they tend to default to NaCl Box's Curve25519/XSalsa20/Poly1305

I'm realizing it would probably be good to walk through the exact procedure using tweetnacl as a guide. If you can sketch out how you'd be calling the decryption code (perhaps using https://github.com/dchest/tweetnacl-js#public-key-authenticated-encryption-box as a reference) we can ensure the on-chain version is compatible.

**Comment by arjunbaokar** [comment]
Let me write up an example in each Node and Go and loop back to you when I've done that.

**Comment by arjunbaokar** [comment]
Here's a quick and dirty example in typescript using tweetnacl-js. I'll write a Go one in a little bit and test them for compatibility, but hopefully this can continue the conversation here.

```
import { box, randomBytes } from 'tweetnacl';

function newNonce() {
  return randomBytes(box.nonceLength);
}

function encodeBase16(arr: Uint8Array): string {
  return Buffer.from(arr).toString('hex');
}

function decodeBase16(s: string): Uint8Array {
  return new Uint8Array(Array.prototype.slice.call(Buffer.from(s, 'hex'), 0));
}

  // ciphertext is `nonce | encryptedMessage` in base64
function encrypt(message: string, recipientPublicKey: string, senderPrivateKey: string): string {
  const nonce = newNonce();
  const messageUint8 = Buffer.from(message);
  const recipientPublicKeyUint8 = decodeBase16(recipientPublicKey);
  const senderPrivateKeyUint8 = decodeBase16(senderPrivateKey);

  /*
    We could explicitly compute the DH secret using before() and after() instead of using box(), which does it under the hood.
    This is demonstrated in the commented code below.

    const sharedKey = box.before(recipientPublicKeyUint8, senderPrivateKeyUint8);
    const encrypted = box.after(messageUint8, nonce, sharedKey)
  */

  const encrypted = box(messageUint8, nonce, recipientPublicKeyUint8, senderPrivateKeyUint8);
  if (!encrypted) throw new Error('failed to encrypt');
  const fullMessage = new Uint8Array(nonce.length + encrypted.length);
  fullMessage.set(nonce);
  fullMessage.set(encrypted, nonce.length);

  return Buffer.from(fullMessage).toString('base64');
}

function decrypt(ciphertext: string, senderPublicKey: string, recipientPrivateKey: string): string {
  const ciphertextUint8 = Buffer.from(ciphertext, 'base64');
  const senderPublicKeyUint8 = decodeBase16(senderPublicKey);
  const recipientPrivateKeyUint8 = decodeBase16(recipientPrivateKey);
  const nonce = ciphertextUint8.slice(0, box.nonceLength);
  const message = ciphertextUint8.slice(box.nonceLength, ciphertext.length);

  /*
    We could explicitly compute the DH secret using before() and after() instead of using open(), which does it under the hood.
    This is demonstrated in the commented code below.

    const sharedKey = box.before(senderPublicKeyUint8, recipientPrivateKeyUint8);
    const encrypted = box.open.after(messageUint8, nonce, sharedKey)
  */
  const decrypted = box.open(message, nonce, senderPublicKeyUint8, recipientPrivateKeyUint8);
  if (!decrypted) throw new Error('failed to decrypt');
  return Buffer.from(decrypted).toString();
}

/*
  ASSUMPTIONS (as per current decisions in the KIP):
  - all keys are in base16
  - all ciphertexts are base64
*/

const message = 'message';
const recipient = box.keyPair();
const sender = box.keyPair();
const encrypted = encrypt(message, encodeBase16(recipient.publicKey), encodeBase16(sender.secretKey));
console.log(encrypted);
const decrypted = decrypt(encrypted, encodeBase16(sender.publicKey), encodeBase16(recipient.secretKey));
console.log(decrypted);
```

**Comment by arjunbaokar** [comment]
Golang:

```
package util

import (
	"io"
	"log"

	crand "crypto/rand"

	"golang.org/x/crypto/nacl/box"
)

func EncryptX25519(message []byte, recipientPublicKey *[32]byte, senderPrivateKey *[32]byte) []byte {
	var nonce [24]byte
	if _, err := io.ReadFull(crand.Reader, nonce[:]); err != nil {
		log.Fatal(err)
	}

	encrypted := box.Seal(nonce[:], message, &nonce, recipientPublicKey, senderPrivateKey)
	return encrypted
}

func DecryptX25519(ciphertext []byte, senderPublicKey *[32]byte, recipientPrivateKey *[32]byte) []byte {
	var nonce [24]byte
	copy(nonce[:], ciphertext[:24])
	decrypted, ok := box.Open(nil, ciphertext[24:], &nonce, senderPublicKey, recipientPrivateKey)
	if !ok {
		log.Fatal("Decryption error.")
	}
	return decrypted
}
```

**Comment by slpopejoy** [comment]
@arjunbaokar thanks for these! I can now research suitability of the nacl box with the Haskell libraries.

The nonce is the most significant detail here, and I don't think the pact primitive should expect any particular format for the ciphertext (e.g. appending to the buffer like in your example), which suggests we need to include the nonce value in the API, ie `decrypt` taking `nonce` along with `public-key`, `private-key` and `ciphertext`.

NB: you might consider having a procedural nonce instead of random, since your larger protocol has things like requests that are unique, etc. A nonce does not need to be random but just unique ([ref](https://crypto.stackexchange.com/questions/3965/what-is-the-main-difference-between-a-key-an-iv-and-a-nonce/3970#3970), [ref](https://crypto.stackexchange.com/questions/8495/what-are-the-requirements-of-a-nonce/8497#8497)) so reusing some other verifiably unique value might be more satisfying and possibly not have to be independently stored.

**Comment by arjunbaokar** [comment]
Agreed, ciphertext format should definitely not be part of the primitive. That API change seems reasonable to me. I think internally we're passing an object with `{ nonce, ciphertext }` as well. To recap, our current API proposition looks like
```
validate-keypair (publicKey:string secretKey:string) -> boolean or err
decrypt (ciphertext:string nonce:string publicKey:string secretKey:string) -> string
```
where ciphertext, nonce, and decrypt's result are base64, while keys are base16.

Presumably, not every decryption algorithm you may support in the future would use a nonce, so would you function overload in that situation? I'm not sure what the Pact way of handing different signatures for the same function name is (if it's allowed at all), so I'll defer to your discretion.

Procedural nonces are a great suggestion; I hadn't thought about that! There's a combination of a few IDs that we could guarantee are unique for encryption.

**Comment by slpopejoy** [comment]
Good stuff, I will continue to research the implementation, and also this KIP seems to be near ready as well, so we will fire off a PR shortly. Thanks!

> Presumably, not every decryption algorithm you may support in the future would use a nonce, so would you function overload in that situation? I'm not sure what the Pact way of handing different signatures for the same function name is (if it's allowed at all), so I'll defer to your discretion.

My hope is we don't support multiple schemes, which is why I'm very happy we're looking at nacl boxes to ensure that this approach is user-friendly. But yes, pact builtins (not user functions though!) can overload, both by type and by argument count, so we can support a different decryption scheme this way.

**Comment by arjunbaokar** [comment]
Sounds great, looking forward to it!

**Comment by slpopejoy** [comment]
Haven't found a good secretbox implementation yet unfortunately so this might take longer than anticipated, I've had to revert to reading the original DJB paper to try to implement the whole xsalsa20poly1305 using xsalsa20 and poly1305 primitives from cryptonite.

Meanwhile I did find one place where xsalsa20 was dropped in favor of chacha20, and it mentions the noise protocol doing this, in tendermint; it claims that xsalsa20 is basically obsolete. I'm still in favor of using xsalsa20 simply because nacl's secretbox is so easy to use. https://github.com/tendermint/tendermint/issues/1124

**Comment by slpopejoy** [comment]
Yeah ... it seems the procedure is anything but clear with `cryptonite`. There are straight nacl bindings in [`saltine`](http://hackage.haskell.org/package/saltine) but I was really hoping to not have to use two crypto libraries. I've [opened an issue with `cryptonite`](https://github.com/haskell-crypto/cryptonite/issues/283) just to be sure I'm not missing something.

**Comment by slpopejoy** [comment]
One alternate suggestion would be to return to the ChaCha20-Poly1305 approach that the tendermint folks at least seemed to think was less obsolete:

- `cryptonite` has a [unit test](https://github.com/haskell-crypto/cryptonite/blob/cdd0821eeef40ca5b9fc20551245fa9d78ffb07a/tests/ChaChaPoly1305.hs#L13) implementing the [reference test from IETF RFC7539](https://tools.ietf.org/html/rfc7539#section-2.4.2)
- `libsodium` has [dedicated variants](https://github.com/jedisct1/libsodium-doc/blob/master/secret-key_cryptography/chacha20-poly1305.md#variants) for the IETF approach
- [libsodium.js](https://www.npmjs.com/package/libsodium-wrappers) is available on npm.
- the corresponding [go library is available.](https://godoc.org/golang.org/x/crypto/chacha20poly1305)

libsodium seems to be perhaps a more production-worthy library than nacl? https://flak.tedunangst.com/post/some-gripes-about-nacl

**Comment by emilypi** [comment]
Judging by the discussion in the Tendermint issue, it seems like sticking with ChaCha20-Poly1305 would be a more future-savvy decision which is already supported in both of our ecosystems. I'm particularly interested in both the support in improved diffusion which seemed to cause issues with the Salsa family.

**Comment by arjunbaokar** [comment]
I believe ChaCha20 was what we brought up in the initial conversation too, which we're still fine with. I just chose nacl to write the original script in because it was super easy, but I'm happy to switch to libsodium.

Do you want me to create an equivalent script to the above with libsodium for compatibility testing?

**Comment by slpopejoy** [comment]
@arjunbaokar great. Nacl was our default choice too as it's what the pact js lib uses so I was a little surprised to see the lack of support in `cryptonite` but that's probably because of the preference for ChaCha20. 

If you want to do the exercise with that, it's certainly not a bad idea for at least one of them so we can ensure we can reproduce the results. We can get started on our end right away however.

**Comment by slpopejoy** [comment]
@arjunbaokar please note the edit to the reference test above, [section 2.8.2](https://tools.ietf.org/html/rfc7539#section-2.8.2) is the correct test that is reproduced in cryptonite.

**Comment by slpopejoy** [comment]
Note that as ChaCha20/Poly1305 is a "modern" authentication scheme (ie AEAD), this complicates our API a little ([ref](https://tools.ietf.org/html/rfc7539#section-2.8)): 

1. AAD must be specified, adding another argument to `decrypt`.
2. Encryption output also produces a 128-bit authentication tag. Either we would supply this as another argument, or expect the ciphertext to have a 128-bit prefix with this.

This adds some data overhead. We should decide if we instead want to simply use ChaCha20 ([ref](https://tools.ietf.org/html/rfc7539#section-2.4)), which simply accepts a key, a nonce, and a counter. (We could hard-code the counter to 0 also, the recommendation says 0, or 1 if using the first block for AEAD).

**Comment by slpopejoy** [comment]
OK, I've got the following two primitives working. Note -- I suggest we now name the primitive `decrypt-cc20p1305` or similar, as it's become very algo-specific. 

```
pact> validate-keypair
native `validate-keypair`
  
  Enforce that the Curve25519 keypair of (PUBLIC,SECRET) match. Key values are
  base-16 strings of length 32.
  
  Type:
  public:string secret:string -> bool
  
  Examples:
  (validate-keypair pubkey privkey)
pact> (validate-keypair "a236ee764da1bde16f3452df78ed0d46d94c0763042330a8341511cfe537da6d" "92702bbc9026d489f0ecefe266d694b9ad321965f3345758d1f937fba8817184")
true
pact> decrypt-cc20p1305
native `decrypt-cc20p1305`
  
  Decrypt a Curve25519/ChaCha20/Poly1305 CIPHERTEXT using NONCE, AAD, PUBLIC-KEY
  and SECRET-KEY. CIPHERTEXT is an unpadded base64url value with the 16-byte
  authentication tag output of the encryption. PUBLIC-KEY and SECRET-KEY are
  base-16 strings of length 32. NONCE is an unpadded base64URL value of a
  24-byte bytestring. AAD is additional authentication data of an unpadded
  base-16 string of any length. Result is unpadded base64URL.
  
  Type:
  ciphertext:string nonce:string aad:string public-key:string secret-key:string -> string
  
  Examples:
  (decrypt-cc20p1305 ciphertext nonce aad pubkey privkey)
pact> (decrypt-cc20p1305 "xvhAzzyGWuWdlA2XW7irq2sEAC6JiHk" "Ka96AovW2JFVrgOK" "616164" "a236ee764da1bde16f3452df78ed0d46d94c0763042330a8341511cfe537da6d" "92702bbc9026d489f0ecefe266d694b9ad321965f3345758d1f937fba8817184")
"bWVzc2FnZQ"
```
The above example decrypts using the supplied keypair, AAD of "aad" (in base16), and a random base64url nonce, the plaintext "message", which in unpadded base64url is "bWVzc2FnZQ".

**Comment by arjunbaokar** [comment]
Sorry for the delay, I had a bunch of other things come up on my plate before the July 4 weekend. Here's a Typescript implementation to compatibility test with. You'll need the `libsodium-wrappers` npm package installed.

```
import sodium from 'libsodium-wrappers'

interface EncryptionResult {
  ciphertext: Buffer;
  nonce: Buffer;
  aad: Buffer;
}

async function encryptX25519cc20p1305(message: Buffer, publicKey: Buffer, privateKey: Buffer) {
  const ADDITIONAL_DATA = "123456" // we can randomize this
  const nonce = sodium.randombytes_buf(sodium.libsodium._crypto_aead_chacha20poly1305_ietf_npubbytes()) as Uint8Array;
  const key = sodium.crypto_box_beforenm(publicKey, privateKey);
  const ciphertext = sodium.crypto_aead_chacha20poly1305_ietf_encrypt(message, ADDITIONAL_DATA, null, nonce, key);
  sodium.memzero(key)

  return {
    ciphertext: Buffer.from(ciphertext),
    nonce: Buffer.from(nonce),
    aad: Buffer.from(ADDITIONAL_DATA)
  }
}

async function decryptX25519cc20p1305(encryptionResult: EncryptionResult, publicKey: Buffer, privateKey: Buffer) {
  const { ciphertext, aad, nonce } = encryptionResult;
  const dhSecretKey = sodium.crypto_box_beforenm(publicKey, privateKey);
  const decrypted: Uint8Array = sodium.crypto_aead_chacha20poly1305_ietf_decrypt(null, ciphertext, aad, nonce, dhSecretKey)
  sodium.memzero(dhSecretKey);
  return Buffer.from(decrypted);
}

async function main() {
  await sodium.ready;

  const plaintext = Buffer.from('test');
  const recipient = sodium.crypto_kx_keypair();
  const sender = sodium.crypto_kx_keypair();
  const encryptionResult = await encryptX25519cc20p1305(plaintext, recipient.publicKey, sender.privateKey);
  const decrypted = await decryptX25519cc20p1305(encryptionResult, sender.publicKey, recipient.privateKey);
  const result = (decrypted.equals(plaintext)) ? 'Success' : 'Failure';
  console.log(result);
}

main()
```

**Comment by arjunbaokar** [comment]
@slpopejoy what KDF are you using to create the shared key?

Another suggestion (if this wasn't already what you meant) -- Do we want to make AAD optional (allow AAD == null)? It lets people choose if they want AE or AEAD, which might be the more flexible implementation of this system, and is also aligned with what libsodium and go's crypto library do.

**Comment by slpopejoy** [comment]
> what KDF are you using to create the shared key?

The pact function does DH on the provided Curve25519 pubkey and privkey to get the shared key. This matches the `box` UX from before, and is lined up with this IP which is all about Curve25519 pub and private keys (e.g. `validate-keypair`). We haven't discussed representing a DH shared key in Pact so I thought I'd keep it the same.

> Do we want to make AAD optional 

No, because that would essentially encourage devs to ignore AAD, and hardcoding `""` is easy enough. An on-blockchain decryption function is always a "decrypt after" challenge-response where the plaintext is no longer sensitive, but in normal unchallenged use, who knows what the use case might be -- AAD might be essential. In any case hardcoding `""` is easy.

**Comment by slpopejoy** [comment]
@arjunbaokar regarding your examples can we get them to use curve25519 pub/priv DH like the pact, and also use unpadded base64url for encoding? Would be great to get a fully-matching roundtrip.

**Comment by arjunbaokar** [comment]
Maybe I'm not being clear or misunderstanding something. My understanding is that DH would just perform a scalar multiplication, whereas [libsodium box uses ScalarMult and HSalsa20 on the result](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c#L42). So my question was whether Pact also does ScalarMult -> HSalsa20, uses ScalarMult -> SomeOtherFunction, or just uses the result of the ScalarMult directly. HSalsa20 seems like it's used to guarantee 512-bit length of the output so it can be used for 2 256-bit keys. Please correct me if any of this doesn't seem correct.

>The pact function does DH on the provided Curve25519 pubkey and privkey to get the shared key.
makes it sound like it's just ScalarMult, but I'd like confirmation.

I agree with the AAD comments; hardcoding `""` seemed more consistent with the other examples on the Pact documentation.

**Comment by slpopejoy** [comment]
I'm not up on the math, so it's hard for me to check -- however as I noted [above](https://github.com/kadena-io/KIPs/issues/5#issuecomment-507089421)  the cryptonite implementation is the IETF one, which as noted there libsodium has a dedicated version to match. I don't think using `box` is the same thing.

**Comment by arjunbaokar** [comment]
For clarity -- I'm referring to ECDH implementation, not the Chacha20Poly1305 libsodium function. The sample code that I shared above uses the libsodium cc20p1305 function already. The [IETF RFC for ECDH on Curve25519](https://tools.ietf.org/html/rfc7748#section-6.1) refers to a KDF being used on the result of the scalar multiplication, and I was asking which KDF Pact's decrypt function uses to create the shared key for cc20p1305. I mentioned box's use of HSalsa20 as an example KDF.

Your comment above seems to only focus on the symmetric step of encryption (and the example cryptonite code uses a hardcoded key, which doesn't help me see how it was derived), unless I am missing something.

**Comment by slpopejoy** [comment]
OK I can confirm that the ECDH KDF in Haskell matches the example in the IETF RFC:
```
   Test vector:

   Alice's private key, a:
     77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a
   Alice's public key, X25519(a, 9):
     8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a
   Bob's private key, b:
     5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb
   Bob's public key, X25519(b, 9):
     de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f
   Their shared secret, K:
     4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742
```

I added a test for this to the PR: https://github.com/kadena-io/pact/pull/564/files#diff-8fe18e11324a0bf59d409a91bfdf12dcR218

which succeeds:
```
λ> _checkRFC7748_6_1
((PublicKey "\133 \240\t\137\&0\167Tt\139}\220\180>\247Z\r\191:\r&8\SUB\244\235\164\169\142\170\155Nj",SecretKey <scrubbed-bytes>),(PublicKey "\222\158\219}{}\193\180\211[a\194\236\228\&57?\131C\200[xgM\173\252~\DC4o\136+O",SecretKey <scrubbed-bytes>),DhSecret <scrubbed-bytes>)
```

**Comment by arjunbaokar** [comment]
Ok, we're matching on that then. Can you send me the encryption keypair you used for the example in [the pact example](https://github.com/kadena-io/KIPs/issues/5#issuecomment-507489758)? I can't get that decrypt to work (sodium seems to think the ciphertext/tag is invalid), and that would help for debugging.

In the meantime, here's an encryption/decryption example with the test keys from RFC7748 (and your above comment) with base64 for plaintext/ciphertext/nonce and base16 keys/aad. These do generate the correct shared key `4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742`.

```
import sodium from 'libsodium-wrappers'

interface EncryptionResult {
  ciphertext: string; // base64
  nonce: string; // base64
  aad: string; // base16
}

async function encryptX25519cc20p1305(message: string, aad: string, publicKey: string, privateKey: string) {
  const messageB = Buffer.from(message, 'base64');
  const aadB = Buffer.from(aad, 'hex');
  const privateKeyB = Buffer.from(privateKey, 'hex');
  const publicKeyB = Buffer.from(publicKey, 'hex');
  const nonce = Buffer.from(sodium.randombytes_buf(sodium.crypto_aead_chacha20poly1305_ietf_NPUBBYTES));
  const key = Buffer.from(sodium.crypto_scalarmult(privateKeyB, publicKeyB));
  const ciphertext = sodium.crypto_aead_chacha20poly1305_ietf_encrypt(messageB, aadB, null, nonce, key);
  sodium.memzero(key)

  return {
    ciphertext: Buffer.from(ciphertext).toString('base64'),
    nonce: Buffer.from(nonce).toString('base64'),
    aad: aadB.toString('hex'),
  }
}

async function decryptX25519cc20p1305(encryptionResult: EncryptionResult, publicKey: string, privateKey: string) {
  const { ciphertext, aad, nonce } = encryptionResult;
  const ciphertextB = Buffer.from(ciphertext, 'base64');
  const nonceB = Buffer.from(nonce, 'base64');
  const aadB = Buffer.from(aad, 'hex');
  const privateKeyB = Buffer.from(privateKey, 'hex');
  const publicKeyB = Buffer.from(publicKey, 'hex');
  const dhSecretKey = Buffer.from(sodium.crypto_scalarmult(privateKeyB, publicKeyB));
  const decrypted: Uint8Array = sodium.crypto_aead_chacha20poly1305_ietf_decrypt(null, ciphertextB, aadB, nonceB, dhSecretKey);
  sodium.memzero(dhSecretKey);
  return Buffer.from(decrypted).toString('base64');
}

async function main() {
  await sodium.ready;

  const plaintext = Buffer.from('message').toString('base64');
  // test keys from https://tools.ietf.org/html/rfc7748#section-6.1
  const aPriv = '77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a';
  const aPub = '8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a';
  const bPriv = '5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb';
  const bPub = 'de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f';
  const aad = '616164'; // "aad" in hex
  const encryptionResult = await encryptX25519cc20p1305(plaintext, aad, bPub, aPriv);
  console.log(encryptionResult);
  const decrypted = await decryptX25519cc20p1305(encryptionResult, aPub, bPriv);
  console.log(decrypted)
}


main()
```

**Comment by slpopejoy** [comment]
OK per discussion added tests for alice+bob pairs from the RFC https://github.com/kadena-io/pact/pull/564/files#diff-8fe18e11324a0bf59d409a91bfdf12dcR262 . 

Verifying that intended output comes for both ways encryption:

λ> _encryptBA >>= _decryptAB
"bWVzc2FnZQ"
λ> _encryptAB >>= _decryptBA
"bWVzc2FnZQ"

**Comment by arjunbaokar** [comment]
Can you also confirm that your test vector matches the one in https://tools.ietf.org/html/rfc7539#appendix-A.5? I don't encrypt to the same ciphertexts using the values in your unit tests, and I can't decrypt your ciphertexts.

Additionally, it seems like you prepend the mac to the ciphertext, whereas sodium appends it. I'm running it in [detached mode](https://libsodium.gitbook.io/doc/secret-key_cryptography/aead/chacha20-poly1305/ietf_chacha20-poly1305_construction#detached-mode), which would be preferred since the caller wouldn't have to slice and re-order the ciphertext based on the library they were using. In our specific case, we'd have to slice and re-order in pact, since that's where we verify decryption.

**Comment by slpopejoy** [comment]
I've switched the PR to append the mac; using your values I get`662d51123e7e881583fa946ef1abb684c6fa1a1c81fc26` (except in base64url).

**Comment by arjunbaokar** [comment]
Looks good, that matches what I have above, and what sodium outputs.

**Comment by slpopejoy** [comment]
Of course, providing separately to the function is better. I'll update for that. (I forgot we aren't offering a pact `encrypt` which would motivate concatenation as the return type of such an operation. As an input to `decrypt` two args are clearly superior).

**Comment by slpopejoy** [comment]
I'd like to come up with a broader rationalization of the KIP in terms of motivation beyond the Finprint use case. To my mind, this is a first step toward supporting different kinds of cryptographic _commitments_ which someday could also include Petersen commitments etc.

In the Finprint case the commitment concept is presented through the storage of the components of the private key which is itself encrypted and stored. The essence of the commitment IMO is the presence of some history that would then be revealed in a challenge process where _that which is decrypted has already been "asserted to" on the blockchain_ through whatever public signatures were enforced at storage time and thereby memorialized.

At some point we would look to make these datatypes in Pact proper but this simply seeks to enable an initial workflow. 

Please comment and give thoughts on this larger topic and we'll open the proper KIP!

**Comment by arjunbaokar** [comment]
I agree with what you've written. Yes, our need for this decrypt primitive is used to verify something that has already been attested to. It can be visualized as a commitment with a shared secret recombination step.

On the note of supporting other commitment schemes, would your path forward involve exposing primitives that validate popular commitment schemes, or providing verification functions for cryptographic primitives as building blocks for commitments? An example: when supporting the "normal" construction of Pedersen commitments, would you expose `validate-pedersen` or expect the contract developer to correctly validate `g^x h^r mod p` with the provided `^` primitive? The latter path seems more flexible to me, and means that Pact would provide a very thin wrapper on top of what sodium/cryptonite-esque libraries expose. The next steps seem like they would be to expose basic Curve25519 math functions like `scalar-mult` so people can build their EC commitment schemes.

This is also in line with the purpose `decrypr-cc20p1305` serves -- it's a primitive in our commitment validation contract function. I also think it's better to expect the developer to handle attestations since blockchain provides a pretty natural way to do that, and different challenge processes will likely have their own deviations (like a TTL on challenges, etc).

**Comment by slpopejoy** [comment]
Finalized in #9
